services:
  - type: web
    name: menugo-frontend
    runtime: static
    branch: master
    rootDir: menugo-frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist

  - type: web
    name: menugo-backends
    runtime: node
    branch: master
    plan: free
    rootDir: menugo-backends
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
